name: Pull Request closed

on:
  pull_request:
    types: [closed]

jobs:
  k6_load_test:
    if: github.event.pull_request.merged == true

    name: k6 Load Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run local k6 test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: test.js
