name: Pull Request

on:
  workflow_dispatch:
    inputs:
      vus:
        required: true

jobs:
  k6_cloud_test:
    name: k6 cloud test run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run k6 cloud test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: test.js
          cloud: true
          token: ${{secrets.K6_API_TOKEN}}
